import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { careerAPI } from '@/services/api';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import toast from 'react-hot-toast';
export default function CareerPage() {
  const qc = useQueryClient();
  const [dj, setDj] = useState(''); const [co, setCo] = useState(''); const [sk, setSk] = useState(''); const [selId, setSelId] = useState<string|null>(null);
  const { data: paths } = useQuery({ queryKey: ['careerPaths'], queryFn: async () => { const { data } = await careerAPI.getPaths(); return data.data; } });
  const { data: roadmaps } = useQuery({ queryKey: ['roadmaps'], queryFn: async () => { const { data } = await careerAPI.getRoadmaps(); return data.data; } });
  const { data: resumes } = useQuery({ queryKey: ['resumes'], queryFn: async () => { const { data } = await careerAPI.getResumes(); return data.data; } });
  const { data: gap } = useQuery({ queryKey: ['gap', selId], queryFn: async () => { if (!selId) return null; const { data } = await careerAPI.getGapAnalysis(selId); return data.data; }, enabled: !!selId });
  const anM = useMutation({ mutationFn: (d: any) => careerAPI.analyze(d), onSuccess: r => { toast.success('Analysis complete!'); setSelId(r.data.data._id); qc.invalidateQueries({ queryKey: ['careerPaths'] }); }, onError: () => toast.error('Failed. Check API key.') });
  const rmM = useMutation({ mutationFn: (id: string) => careerAPI.generateRoadmap({ careerPathId: id }), onSuccess: () => { toast.success('Roadmap generated!'); qc.invalidateQueries({ queryKey: ['roadmaps'] }); }, onError: () => toast.error('Failed') });
  const rsM = useMutation({ mutationFn: (id?: string) => careerAPI.generateResume({ careerPathId: id }), onSuccess: () => { toast.success('Resume generated!'); qc.invalidateQueries({ queryKey: ['resumes'] }); }, onError: () => toast.error('Failed') });
  return (
    <div className="space-y-6"><div><h1 className="text-3xl font-bold">🚀 AI Career Roadmap & Resume Builder</h1><p className="text-muted-foreground">Enter dream job, let AI create your plan</p></div>
      <Tabs defaultValue="analyze" className="space-y-4"><TabsList className="flex-wrap"><TabsTrigger value="analyze">Analyze</TabsTrigger><TabsTrigger value="gap">Gap Analysis</TabsTrigger><TabsTrigger value="roadmap">Roadmaps ({roadmaps?.length||0})</TabsTrigger><TabsTrigger value="resume">Resume</TabsTrigger></TabsList>
        <TabsContent value="analyze" className="space-y-4">
          <Card><CardHeader><CardTitle>Career Analysis</CardTitle><CardDescription>Enter your dream job and optionally upload syllabus</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>Dream Job</Label><Input placeholder="e.g. Software Engineer" value={dj} onChange={e=>setDj(e.target.value)} /></div><div className="space-y-2"><Label>Target Company</Label><Input placeholder="e.g. Google" value={co} onChange={e=>setCo(e.target.value)} /></div></div><div className="space-y-2"><Label>Your Skills (comma-separated)</Label><Input placeholder="e.g. JavaScript, React, Python" value={sk} onChange={e=>setSk(e.target.value)} /></div><div className="space-y-2"><Label>Upload Syllabus (PDF, optional)</Label><Input type="file" accept=".pdf" onChange={async e => { const f=e.target.files?.[0]; if(!f||!dj||!co) { toast.error('Fill fields first'); return; } const fd=new FormData(); fd.append('syllabus',f); fd.append('dreamJob',dj); fd.append('company',co); try { const {data}=await careerAPI.uploadSyllabus(fd); toast.success('Parsed!'); setSelId(data.data._id); qc.invalidateQueries({queryKey:['careerPaths']}); } catch { toast.error('Upload failed'); }}} /></div><Button onClick={()=>{ if(!dj||!co){toast.error('Enter job & company');return;} anM.mutate({dreamJob:dj,company:co,skills:sk.split(',').map(s=>s.trim()).filter(Boolean)});}} disabled={anM.isPending}>{anM.isPending?'🔄 Analyzing...':'🔍 Analyze'}</Button></CardContent></Card>
          {(paths||[]).length>0 && <div className="space-y-4"><h2 className="text-xl font-semibold">Your Career Paths</h2>{paths.map((p:any)=><Card key={p._id} className={`cursor-pointer hover:shadow-md ${selId===p._id?'ring-2 ring-primary':''}`} onClick={()=>setSelId(p._id)}><CardHeader><CardTitle className="text-lg">{p.dreamJob} at {p.company}</CardTitle></CardHeader><CardContent><div className="flex flex-wrap gap-1">{p.requiredSkills?.slice(0,8).map((s:string)=><Badge key={s} variant="secondary">{s}</Badge>)}</div><div className="mt-3 flex gap-2"><Button size="sm" variant="outline" onClick={e=>{e.stopPropagation();rmM.mutate(p._id)}} disabled={rmM.isPending}>📋 Roadmap</Button><Button size="sm" variant="outline" onClick={e=>{e.stopPropagation();rsM.mutate(p._id)}} disabled={rsM.isPending}>📄 Resume</Button></div></CardContent></Card>)}</div>}
        </TabsContent>
        <TabsContent value="gap">{gap?<Card><CardHeader><CardTitle>Gap Analysis</CardTitle><CardDescription>Match: {(gap as any).overallMatch}%</CardDescription></CardHeader><CardContent className="space-y-4"><Progress value={(gap as any).overallMatch} className="h-4" indicatorClassName={(gap as any).overallMatch>=70?'bg-green-500':'bg-amber-500'} /><div className="grid gap-6 md:grid-cols-2"><div><h3 className="mb-2 font-semibold text-green-700">✅ Matched</h3><div className="flex flex-wrap gap-1">{(gap as any).matchedSkills?.map((s:string)=><Badge key={s} variant="success">{s}</Badge>)}</div></div><div><h3 className="mb-2 font-semibold text-red-700">❌ Missing</h3><div className="space-y-2">{(gap as any).missingSkills?.map((s:any)=><div key={s.skill} className="flex items-center justify-between rounded-md bg-red-50 p-2"><span className="font-medium">{s.skill}</span><div className="flex gap-1"><Badge variant={s.priority==='high'?'destructive':'outline'}>{s.priority}</Badge><Badge variant="outline">{s.timeEstimate}</Badge></div></div>)}</div></div></div></CardContent></Card>:<Card><CardContent className="py-12 text-center text-muted-foreground">Select a career path first</CardContent></Card>}</TabsContent>
        <TabsContent value="roadmap" className="space-y-4">{(roadmaps||[]).length===0?<Card><CardContent className="py-12 text-center text-muted-foreground">No roadmaps yet</CardContent></Card>:roadmaps.map((rm:any)=><Card key={rm._id}><CardHeader><CardTitle>{rm.duration}-Month Roadmap</CardTitle><div className="flex items-center gap-2"><Progress value={rm.progress} className="flex-1" /><span className="text-sm">{rm.progress}%</span></div></CardHeader><CardContent><div className="space-y-4">{rm.months?.map((m:any)=><div key={m.month} className="rounded-lg border p-4"><h3 className="mb-2 font-semibold">Month {m.month}: {m.title}</h3><div className="grid gap-3 md:grid-cols-2"><div><p className="text-sm font-medium text-muted-foreground">Goals</p><ul className="text-sm list-disc list-inside">{m.goals?.map((g:string,i:number)=><li key={i}>{g}</li>)}</ul></div><div><p className="text-sm font-medium text-muted-foreground">Skills</p><div className="flex flex-wrap gap-1">{m.skills?.map((s:string)=><Badge key={s} variant="outline" className="text-xs">{s}</Badge>)}</div></div></div></div>)}</div></CardContent></Card>)}</TabsContent>
        <TabsContent value="resume" className="space-y-4"><Button onClick={()=>rsM.mutate(selId||undefined)} disabled={rsM.isPending}>{rsM.isPending?'🔄 Generating...':'✨ AI Generate Resume'}</Button>{(resumes||[]).map((r:any)=><Card key={r._id}><CardHeader><CardTitle>📄 {r.content?.name||'Resume'}</CardTitle></CardHeader><CardContent className="space-y-3">{r.content?.summary&&<p className="text-sm">{r.content.summary}</p>}{r.content?.skills?.length>0&&<div><h3 className="font-semibold mb-1">Skills</h3>{r.content.skills.map((c:any)=><div key={c.category} className="mb-1"><span className="text-sm font-medium">{c.category}: </span><span className="text-sm">{c.items?.join(', ')}</span></div>)}</div>}{r.content?.projects?.length>0&&<div><h3 className="font-semibold mb-1">Projects</h3>{r.content.projects.map((p:any)=><div key={p.name} className="mb-2 rounded-md bg-muted p-2"><p className="font-medium text-sm">{p.name}</p><p className="text-xs text-muted-foreground">{p.description}</p></div>)}</div>}</CardContent></Card>)}</TabsContent>
      </Tabs>
    </div>
  );
}
