import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { groupAPI } from '@/services/api';
import { useAuthStore } from '@/stores/authStore';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Label } from '@/components/ui/label';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import toast from 'react-hot-toast';
const RI:Record<string,string> = {timekeeper:'⏱️',notetaker:'📝',questionmaster:'❓',presenter:'🎤',member:'👤'};
export default function GroupsPage() {
  const { user } = useAuthStore(); const qc = useQueryClient();
  const [show, setShow] = useState(false); const [nm, setNm] = useState(''); const [desc, setDesc] = useState(''); const [goals, setGoals] = useState(''); const [skills, setSkills] = useState(''); const [ndf, setNdf] = useState(user?.learningTrack === 'neurodivergent');
  const { data: my } = useQuery({ queryKey: ['myGroups'], queryFn: async () => { const { data } = await groupAPI.getGroups(); return data.data; } });
  const { data: matches } = useQuery({ queryKey: ['groupMatches'], queryFn: async () => { const { data } = await groupAPI.match(); return data.data; } });
  const crM = useMutation({ mutationFn: groupAPI.create, onSuccess: () => { toast.success('Created!'); setShow(false); qc.invalidateQueries({ queryKey: ['myGroups'] }); } });
  const jnM = useMutation({ mutationFn: groupAPI.join, onSuccess: () => { toast.success('Joined!'); qc.invalidateQueries({ queryKey: ['myGroups'] }); qc.invalidateQueries({ queryKey: ['groupMatches'] }); }, onError: (e: any) => toast.error(e.response?.data?.message || 'Failed') });
  return (
    <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-bold">📚 AI Study Groups</h1><p className="text-muted-foreground">Smart matching by skills, goals & accessibility</p></div><Button onClick={()=>setShow(true)}>+ Create Group</Button></div>
      <Tabs defaultValue="my" className="space-y-4"><TabsList><TabsTrigger value="my">My Groups ({my?.length||0})</TabsTrigger><TabsTrigger value="discover">Discover</TabsTrigger><TabsTrigger value="matches">AI Matches</TabsTrigger></TabsList>
        <TabsContent value="my" className="space-y-4">{(my||[]).length===0?<Card><CardContent className="py-12 text-center text-muted-foreground">No groups yet. Create or join one!</CardContent></Card>:my.map((g:any)=><Card key={g._id}><CardHeader><div className="flex items-center justify-between"><div><CardTitle className="flex items-center gap-2">{g.name}{g.neurodivergentFriendly&&<Badge variant="secondary">♿</Badge>}</CardTitle><CardDescription>{g.description||'No description'}</CardDescription></div><Badge>{g.members?.length||0}/{g.maxMembers}</Badge></div></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-1">{g.goals?.map((x:string)=><Badge key={x} variant="outline">{x}</Badge>)}</div>{g.accessibilityFeatures?.length>0&&<div className="flex flex-wrap gap-1">{g.accessibilityFeatures.map((f:string)=><Badge key={f} variant="secondary" className="text-xs">{f.replace(/_/g,' ')}</Badge>)}</div>}<div className="flex flex-wrap gap-2">{g.members?.map((m:any)=><div key={m.userId?._id||m.userId} className="flex items-center gap-1 rounded-full bg-muted px-3 py-1 text-sm"><span>{RI[m.role]||'👤'}</span><span>{m.userId?.name||'Member'}</span><Badge variant="outline" className="text-xs ml-1">{m.role}</Badge></div>)}</div></CardContent></Card>)}</TabsContent>
        <TabsContent value="discover" className="space-y-4">{(matches?.availableGroups||[]).length===0?<Card><CardContent className="py-12 text-center text-muted-foreground">No groups available. Create your own!</CardContent></Card>:matches.availableGroups.map((g:any)=><Card key={g._id}><CardContent className="flex items-center justify-between pt-6"><div><h3 className="font-semibold">{g.name}</h3><p className="text-sm text-muted-foreground">{g.members?.length}/{g.maxMembers} members</p><div className="flex flex-wrap gap-1 mt-1">{g.skills?.map((s:string)=><Badge key={s} variant="outline" className="text-xs">{s}</Badge>)}</div></div><Button size="sm" onClick={()=>jnM.mutate(g._id)} disabled={jnM.isPending}>Join</Button></CardContent></Card>)}</TabsContent>
        <TabsContent value="matches" className="space-y-4"><h3 className="text-lg font-semibold">Suggested Partners</h3>{(matches?.suggestedUsers||[]).length===0?<p className="text-muted-foreground">No matches</p>:<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{matches.suggestedUsers.map((u:any)=><Card key={u.id}><CardContent className="pt-6 space-y-2"><div className="flex items-center justify-between"><span className="font-semibold">{u.name}</span><Badge variant={u.compatibilityScore>=70?'success':'outline'}>{u.compatibilityScore}% match</Badge></div><div className="flex flex-wrap gap-1">{u.skills?.map((s:string)=><Badge key={s} variant="secondary" className="text-xs">{s}</Badge>)}</div>{u.learningTrack==='neurodivergent'&&<Badge variant="outline">{u.neurodivergentType}</Badge>}</CardContent></Card>)}</div>}</TabsContent>
      </Tabs>
      <Dialog open={show} onOpenChange={setShow}><DialogContent><DialogHeader><DialogTitle>Create Study Group</DialogTitle></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label>Name</Label><Input value={nm} onChange={e=>setNm(e.target.value)} /></div><div className="space-y-2"><Label>Description</Label><Textarea value={desc} onChange={e=>setDesc(e.target.value)} /></div><div className="space-y-2"><Label>Goals (comma-separated)</Label><Input value={goals} onChange={e=>setGoals(e.target.value)} /></div><div className="space-y-2"><Label>Skills (comma-separated)</Label><Input value={skills} onChange={e=>setSkills(e.target.value)} /></div><div className="flex items-center gap-2"><Switch checked={ndf} onCheckedChange={setNdf} id="ndf" /><Label htmlFor="ndf">♿ Neurodivergent Friendly</Label></div></div><DialogFooter><Button variant="outline" onClick={()=>setShow(false)}>Cancel</Button><Button onClick={()=>crM.mutate({name:nm,description:desc,goals:goals.split(',').map(g=>g.trim()).filter(Boolean),skills:skills.split(',').map(s=>s.trim()).filter(Boolean),neurodivergentFriendly:ndf})} disabled={!nm||crM.isPending}>Create</Button></DialogFooter></DialogContent></Dialog>
    </div>
  );
}
